### ISSUE TITLE
Provider crash 1.3.4

### ISSUE THREAD

**Issue by iehrenwaldDK** [logicmonitor/terraform-provider-logicmonitor#30]
Attempted to delete a resource of type logicmonitor_collector and got:

│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-logicmonitor_v1.3.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bc5a8]

goroutine 29 [running]:
github.com/logicmonitor/terraform-provider-logicmonitor/logicmonitor.deleteCollector(0xc000540850, 0x121ea20, 0xc000380420, 0x24, 0x2134e60)
        github.com/logicmonitor/terraform-provider-logicmonitor/logicmonitor/resource_collector.go:189 +0x168
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0006047e0, 0xc000998cd0, 0xc0003daa40, 0x121ea20, 0xc000380420, 0x40cb01, 0x20, 0x1373060)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:283 +0x498
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000916180, 0xc0006eda38, 0xc000998cd0, 0xc0003daa40, 0x2134e60, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00011c0d0, 0x16f7760, 0xc000465ce0, 0xc000540380, 0xc00011c0d0, 0xc000465ce0, 0xc000617ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x13c83c0, 0xc00011c0d0, 0x16f7760, 0xc000465ce0, 0xc0009a0360, 0x0, 0x16f7760, 0xc000465ce0, 0xc00054c300, 0xf8)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004556c0, 0x1705e20, 0xc0006c2600, 0xc0009a2200, 0xc0008a84e0, 0x20f3fc0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0004556c0, 0x1705e20, 0xc0006c2600, 0xc0009a2200, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008901b0, 0xc0004556c0, 0x1705e20, 0xc0006c2600, 0xc0009a2200)
        google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.30.0/server.go:832 +0x204

Error: The terraform-provider-logicmonitor_v1.3.4 plugin crashed!

Terraform 0.15.5, LM provider 1.3.4.  Running the same destroy again reproduces the crash.

**Comment by iehrenwaldDK** [comment]
Following up, it looks like it is crashing because when the collector is created via logicmonitor_collector, a monitored device within LM is also created, and the collector ties back to that device.  Deleting the monitored device (and then really deleting it via the recently deleted list) allows the tf destroy to complete.  

It would be nice if destroying the logicmonitor_collector resource also removed the monitored device tied to it.
